### PR TITLE
Fixed Orbstack cloud-init error

### PR DESCRIPTION
**Pull request by rcastley**

### CODE REVIEW

**Comment by wpgrant** [comment]
I haven't used this so I will need to trust it's good. (If there is any concern with the change let's have someone else review as well.

**Review by billg-splunk — APPROVED** [review]

**Comment by billg-splunk** [comment]
I approved to avoid delays, but I haven't worked with orbstack yet so if there are any concerns with the changes I encourage getting a 2nd reviewer.

**Comment by rcastley** [comment]
@billg-splunk The change was purely how the default `splunk` user gets created

https://github.com/splunk/observability-workshop/pull/275/files

No breaking change and doesn't affect anything public.

**Comment by billg-splunk** [comment]
> @billg-splunk The change was purely how the default `splunk` user gets created
> 
> https://github.com/splunk/observability-workshop/pull/275/files
> 
> No breaking change and doesn't affect anything public.

Great -- just wanted you to know I didn't actually test it. ;-)

**Pull request merged**
